title: noltarium-documentation-theme 
description: >
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  posts:
    output: true
  presentation:
    output: true
#  articles:
#    output: true

defaults:
  - scope:
      path: "articles"
      #type: articles
    values:
      layout: site/article
      toc: true
  - scope:
      type: presentation
    values:
      layout: presentation/presentation

#mermaid:
#  src: '/js/mermaid.min.js'

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - bootstrap
  - jekyll-feed
  #- jekyll-last-modified-at
  - jemoji
  - jekyll-sitemap
  - jekyll-sass-converter
  - jekyll-coffeescript
  - jekyll-tidy
  - jekyll-toc
  - jekyll-plantuml
#  - jekyll-mermaid

exclude:
  - Gemfile
  - Rakefile
  - Dockerfile
  - Gemfile.lock
  - vendor
  - Procfile
  - Rakefile
  - config.ru
  - test

sass:
    sass_dir: _sass
ditaa_output_directory: /assets/images/ditaa


permalink: /blog/:year/:month/:day/:title/


#asciidoc:
#  ext: adoc
#keep_files:
#  - images

#asciidoctor:
#  base_dir: :docdir
#  safe: unsafe
#  attributes:
#    imagesdir: /images

#include:
#  - images
timezone: UTC
paginate: 5          # Posts per page on the blog index
paginate_path: "blog/posts/:num"  # Directory base for pagination URLs eg. /posts/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles
excerpt_separator: "<!--more-->"
category_dir: /blog/categories

emptyArray: []

#ditaa_output_directory: /assets/images/ditaa

jekyll-archives:
  enabled: all
  layouts:
    year: 'site/archive/year-archive'
    month: 'site/archive/month-archive'
    day: 'site/archive/day-archive'
    tag: 'site/archive/tag-archive-layout'
  permalinks:
    year: '/blog/:year/'
    month: '/blog/:year/:month/'
    day: '/blog/:year/:month/:day/'
    tag: '/blog/tag/:name/'
    category: '/blog/categories/:name/'
